default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shithub_development

test:
  <<: *default
  database: shithub_test

production:
  <<: *default
  database: shithub_production
  username: 
  password:
